// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmT8kR6BfZAH9n8lj5dp2x9jfdo9POxs4',
    appId: '1:592788505898:web:e81761791410fd5c748a53',
    messagingSenderId: '592788505898',
    projectId: 'tugas-mobprog-5f074',
    authDomain: 'tugas-mobprog-5f074.firebaseapp.com',
    storageBucket: 'tugas-mobprog-5f074.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6R_UQN6YcPfBXxXTi94Tx-ucYVCnJxic',
    appId: '1:592788505898:android:124a4bdd7608b1e8748a53',
    messagingSenderId: '592788505898',
    projectId: 'tugas-mobprog-5f074',
    storageBucket: 'tugas-mobprog-5f074.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4uvSD1kRRbE1hc2d2m2eHBueDRAIiuNU',
    appId: '1:592788505898:ios:4346243681500724748a53',
    messagingSenderId: '592788505898',
    projectId: 'tugas-mobprog-5f074',
    storageBucket: 'tugas-mobprog-5f074.appspot.com',
    iosClientId: '592788505898-krguqqc127gnakj3b7l93h5r4c1m7nvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.localNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4uvSD1kRRbE1hc2d2m2eHBueDRAIiuNU',
    appId: '1:592788505898:ios:4346243681500724748a53',
    messagingSenderId: '592788505898',
    projectId: 'tugas-mobprog-5f074',
    storageBucket: 'tugas-mobprog-5f074.appspot.com',
    iosClientId: '592788505898-krguqqc127gnakj3b7l93h5r4c1m7nvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.localNotification',
  );
}
